apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensy-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expensy-backend
  template:
    metadata:
      labels:
        app: expensy-backend
    spec:
      containers:
      - name: expensy-backend
        image: romainconfavreux/expensy_backend:latest
        ports:
        - containerPort: 8080
        env:
            - name: DATABASE_URI
              value: "mongodb://root:example@mongo:27017"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "someredispassword"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensy-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expensy-frontend
  template:
    metadata:
      labels:
        app: expensy-frontend
    spec:
      containers:
      - name: expensy-frontend
        image: romainconfavreux/expensy_frontend:latest
        ports:
        - containerPort: 3000
