name: Build and Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger workflow on push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    # Build Docker image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Check secrets are passed
      run: |
        echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "Token is set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push backend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend:latest ./expensy_backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend:latest

    - name: Build and Push frontend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/expensy_frontend:latest ./expensy_frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/expensy_frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    # Set up AWS CLI for EKS deployment
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-west-3  # Adjust your region

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Update Kubeconfig
      run: eksctl utils write-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region eu-west-3


    # Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/deployment.yaml  # Adjust path to your deployment.yaml
        
