name: Build and Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger workflow on push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    # Build Docker image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
    
    - name: Check secrets are passed
      run: |
        echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "Token is set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push backend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend:latest ./expensy_backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend:latest

    - name: Build and Push frontend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/expensy_frontend:latest ./expensy_frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/expensy_frontend:latest

    # Set up AWS CLI for EKS deployment
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-west-3  # Adjust your region

    # Configure kubectl to access EKS cluster
    - name: Set up kubectl
      uses: aws-actions/eks-kubeconfig-action@v1
      with:
        cluster-name: ${{ secrets.EKS_CLUSTER_NAME }}

    # Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml  #Adjust path to your deployment.yaml
        
